spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loadbooking
    username: amritansh
    password: yourpassword
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
